const conversationStarters = {
  default: [
    'When this is over, I’m really looking forward to….',
    'What I miss the most about being at the office is...',
    'I’ve just discovered this amazing playlist/artist on spotify',
    'My new favorite restaurants that deliver are...',
    'My astrological sign doesn’t match my personality because...',
    'What I like most about my astrological sign is...',
    'I have a great happy hour story',
    'At happy hours I usually...',
    'Last year I...',
    'As a kid, I used to love...',
    'One of my guilty pleasures is...',
    'My favorite instagram accounts are...',
    'The coolest trip I’ve ever been on…',
    'The biggest pickle I’ve ever gotten myself into while traveling was...',
    'The time I felt most fortunate about my life was...',
    'Party or Netflix?',
    'The most incredible person I’ve ever met was...',
    'The weirdest thing I’ve ever eaten was...',
  ],
  'pt-BR': [
    'O que mais quero fazer quando a quarentena acabar...',
    'O que eu mais sinto falta em ir pro escritório...',
    'No meu spotify só anda tocando …',
    'To muito viciado(a) nas músicas…',
    'Amo o restaurante...',
    'O lugar que eu mais almoço por aqui é... ',
    'Meu signo não tem nada haver comigo, porque…',
    'O que eu mais gosto no meu signo..',
    'Tenho uma história muito boa de um happy hour…',
    'No happy hour eu costumo…',
    'Ano passado eu...',
    'Quando eu era criança eu curtia muito…',
    'Um guilty pleasure meu é…',
    'Sempre vejo os stories…',
    'A viagem mais animal que eu já fiz foi…',
    'O perrengue mais doido que eu já passei viajando foi…',
    'As vezes que eu mais me senti privilegiado(a) foi…',
    'Não gostei muito quando cortei meu cabelo…',
    'Balada ou Netflix?',
    'A pessoa mais incrível que eu já conheci…',
    'Meu maior sonho é…',
    'A comida mais esquisita que eu já comi foi...',
  ],
};

const defaultMessage = {
  default: '*Don’t let social distancing bring you down. Catch up with your team, feel all warm and fuzzy inside over Tapioca.*',
  'pt-BR': 'Mais que um café ☕️, uma pipoca 🍿 ou uma tapioca 🍙 essa é uma ferramenta  pra  marcar papos à distância com os colegas de trabalho do dia a dia.',
}

module.exports = {
  conversationStarters,
  defaultMessage,
};
