AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TapiocaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tapioca.handler
      Runtime: nodejs12.x